name: Public Bridge

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      image:
        required: true
        type: string

jobs:
  trigger-private:
    runs-on: ubuntu-latest

    steps:
      - name: Call private workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PRIVATE_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/TU-ORG/TU-REPO/actions/workflows/private.yml/dispatches \
            -d '{
              "ref": "main",
              "inputs": {
                "username": "${{ inputs.username }}",
                "image": "${{ inputs.image }}"
              }
            }'
